[tool.poetry]
name = "pyasync-orm"
version = "0.1.0"
description = "An async ORM."
authors = ["Ron Williams <rnwprogramming@gmail.com>"]
license = "MIT License"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
